number = 17
slug = "top-level-st"
status = "completed"
description = """
# Step: top-level-st

Add `main` blocks to the `.st` source format so a compl..."""
role = "production"
context_files = []
created_at = "2026-04-26T11:52:41"
completed_at = "2026-04-26T13:51:28"
task_type = "production"
commits = ["05288263bd4009fa42bc63a748e1ceba496e7dc1"]
