#!/usr/bin/awk -f
# stc.awk - COR24 Smalltalk source compiler for v0
#
# Reads a .st file on stdin, writes an image_*.bas file to stdout.
# Output format matches what src/vm.bas's read_and_install_methods
# (line 10800) consumes: a bootstrap GOSUB header plus DATA records
# of <class> <selector> <bytecount> <bytes...> terminated by -1.
#
# Syntax (subset, see docs/st-source.md):
#   class CLASSNAME [slots VAR1 VAR2 ...]
#   method SELECTOR
#     <statement>
#     <statement>
#   method ...
#   class ...
#   end
#
# Statements:
#   ^ <expr>            (return)
#   var := <expr>       (assign to slot)
#   primitive N         (primitive method body shortcut)
#
# Expressions: atom { binop atom } left-to-right, no parens.
# Atom: self | integer | slot-name.
# Binops: + - * < =  (must be in selector table).

BEGIN {
  # Selector ID table.  Keep aligned with docs/st-source.md.
  sel["+"]  = 1
  sel["-"]  = 2
  sel["*"]  = 3
  sel["<"]  = 4
  sel["print"]            = 5
  sel["init"]             = 6
  sel["incr"]             = 7
  sel["value"]            = 8
  sel["ifTrue:ifFalse:"]  = 9
  sel["at:"]              = 10
  sel["at:put:"]          = 11
  sel["="]                = 12
  sel["new"]              = 13
  sel["max:"]             = 14
  sel["fact"]             = 15

  # Class ID table.
  cls["Object"]            = 0
  cls["Class"]             = 1
  cls["SmallInteger"]      = 2
  cls["True"]              = 3
  cls["False"]             = 4
  cls["UndefinedObject"]   = 5
  cls["Array"]             = 6
  cls["Symbol"]            = 7
  cls["Method"]            = 8
  cls["Block"]             = 9
  cls["Counter"]           = 10
  cls["BoundedCounter"]    = 11

  # Compiler state.
  cur_class = ""
  cur_slot_n = 0
  cur_method = ""
  body_n = 0
  meth_n = 0
}

# Strip comments and trailing periods; normalise whitespace.
{
  sub(/#.*$/, "")
  gsub(/\./, "")
  gsub(/\t/, " ")
  sub(/^[ ]+/, "")
  sub(/[ ]+$/, "")
}

NF == 0 { next }

# class CLASSNAME [slots V1 V2 ...]
$1 == "class" {
  finish_method()
  finish_class()
  cur_class = $2
  if (!(cur_class in cls)) {
    print "stc: unknown class: " cur_class > "/dev/stderr"
    exit 1
  }
  cur_slot_n = 0
  if (NF >= 4 && $3 == "slots") {
    for (i = 4; i <= NF; i++) cur_slots[cur_slot_n++] = $i
  }
  next
}

# method SELECTOR
$1 == "method" {
  finish_method()
  cur_method = $2
  if (!(cur_method in sel)) {
    print "stc: unknown selector: " cur_method > "/dev/stderr"
    exit 1
  }
  body_n = 0
  next
}

# end
$1 == "end" {
  finish_method()
  finish_class()
  next
}

# primitive N
$1 == "primitive" {
  body[body_n++] = 13           # PRIMITIVE
  body[body_n++] = $2 + 0
  body[body_n++] = 8            # RETURN_TOP
  next
}

# ^ <expr>
$1 == "^" {
  compile_expr_at(2)
  body[body_n++] = 8            # RETURN_TOP
  next
}

# var := <expr>
$2 == ":=" {
  compile_expr_at(3)
  body[body_n++] = 6            # STORE_FIELD
  body[body_n++] = slot_index($1)
  next
}

{
  print "stc: cannot compile line: " $0 > "/dev/stderr"
  exit 1
}

function finish_method(    i) {
  if (cur_method == "") return
  m_class[meth_n] = cls[cur_class]
  m_sel[meth_n] = sel[cur_method]
  m_len[meth_n] = body_n
  for (i = 0; i < body_n; i++) m_body[meth_n, i] = body[i]
  meth_n++
  cur_method = ""
  body_n = 0
}

function finish_class() {
  cur_class = ""
  cur_slot_n = 0
}

function compile_atom(a,    n) {
  if (a == "self") {
    body[body_n++] = 1          # PUSH_SELF
  } else if (a ~ /^-?[0-9]+$/) {
    body[body_n++] = 12         # PUSH_INT
    body[body_n++] = a + 0
  } else {
    n = slot_index(a)
    if (n < 0) {
      print "stc: unknown name: " a > "/dev/stderr"
      exit 1
    }
    body[body_n++] = 5          # PUSH_FIELD
    body[body_n++] = n
  }
}

function compile_expr_at(idx,    i) {
  i = idx
  compile_atom($i)
  i++
  while (i + 1 <= NF) {
    if (!($i in sel)) {
      print "stc: unknown binary selector: " $i > "/dev/stderr"
      exit 1
    }
    compile_atom($(i+1))
    body[body_n++] = 7          # SEND
    body[body_n++] = sel[$i]
    body[body_n++] = 1          # argc 1
    i += 2
  }
}

function slot_index(name,    i) {
  for (i = 0; i < cur_slot_n; i++) if (cur_slots[i] == name) return i
  return -1
}

END {
  finish_method()
  finish_class()

  # Header.
  print "100 REM === IMAGE GENERATED BY tools/stc.awk =================="
  print "110 GOSUB 10100"
  print "115 GOSUB 10700"
  print "120 RESTORE"
  print "125 GOSUB 10800"
  print "130 RETURN"

  # DATA records starting at line 500.
  ln = 500
  for (i = 0; i < meth_n; i++) {
    line = ln " DATA " m_class[i] ", " m_sel[i] ", " m_len[i]
    for (j = 0; j < m_len[i]; j++) line = line ", " m_body[i, j]
    print line
    ln += 5
  }
  print ln " DATA -1, 0, 0"
}
